### ISSUE TITLE
pkgdown

### ISSUE THREAD

**Issue by wibeasley** [nlsy-links/NlsyLinks#34]
Create online doc w/ https://github.com/hadley/pkgdown

**Comment by wibeasley** [comment]
@jrodgers28, @mhunter1, @smasongarrison, @pgok15, & @DavidBard,
check out the new website.  I tried to keep the material as constant as possible.  This uses [pkgdown](https://pkgdown.r-lib.org/index.html) in the hopes that it's easier to keep the documentation up-to-date with the package itself.  

There are some things that need to be smoothed (eg, broken relative links --running list in #57), but does anyone have opinions in the meantime?

http://nlsy-links.github.io/NlsyLinks/

**Comment by jrodgers28** [comment]
Will -- got it now.  The link wasn't displayed off my Vanderbilt e-mail, only off my OU e-mail.


Is there some way to link this site to the first one that comes up when you google "nlsy links"?  We could lose some folks who would do that, and not find the new site.


This looks good, and close enough to old format (very close, to my eye) that regular users will be comfortable.


Joe


Joe Rodgers

Department of Psychology and Human Development

Peabody College

Vanderbilt University

239 Appleton Place #552

Hobbs 202C

Nashville TN 37203


Department of Psychology

University of Oklahoma

Norman OK 73019

405-816-2941


________________________________

**Comment by wibeasley** [comment]
@jrodgers28 

>The link wasn't displayed off my Vanderbilt e-mail, only off my OU e-mail.

I always recommend hitting the "View it on GitHub" link at the bottom of the email notification, so you're taking directly to the page of the GitHub issue.

> Is there some way to link this site to the first one that comes up when you google "nlsy links"?  We could lose some folks who would do that, and not find the new site.

I agree that's a problem, and was on my checklist (see #57).  How does the stub (at the [old location](https://liveoak.github.io/NlsyLinks/)) look now?  

I tried to make it very easy to change too:

https://github.com/LiveOak/NlsyLinks/blob/master/docs/index.html

![image](https://user-images.githubusercontent.com/1372890/59869798-cea80100-9359-11e9-9da2-5b2193e8e9ae.png)
