### ISSUE TITLE
Dedicated GitHub organization

### ISSUE THREAD

**Issue by wibeasley** [nlsy-links/NlsyLinks#55]
@jrodgers28, @mhunter1, @smasongarrison, @pgok15, & @DavidBard , we've discussed creating a new GitHub organization that's dedicated  to our family of research.  I think that's more representative than my private company's organization (*ie*, (Howard) `LiveOak`). 

**Please propose and/or vote on a name.**

This would show up in at least three places
1. The repo's home & URL: https://github.com/LiveOak/NlsyLinks
1. The static website's url: http://liveoak.github.io/NlsyLinks/
1. The Google Group's name (see #54)

I'm currently leaning towards "nlsy-links" (which essentially the name of the package).  I'd like this name/organization to live beyond the current grant, which may step outside of the NLSY.  Also, if one of you takes over this line of research, I'd like to transfer ownership (of the group & GitHub org) at that time; it should help maintain any following.

I'd like to do this in the next day or two, so things can be ready before the Stockholm presentations.

**Comment by jrodgers28** [comment]
I like nlsy-links fine.  Joe


Joe Rodgers

Department of Psychology and Human Development

Peabody College

Vanderbilt University

239 Appleton Place #552

Hobbs 202C

Nashville TN 37203


Department of Psychology

University of Oklahoma

Norman OK 73019

405-816-2941


________________________________

**Comment by wibeasley** [comment]
@jrodgers28  or others, please tell me what you'd like in these fields

![image](https://user-images.githubusercontent.com/1372890/59808555-5fcb9900-92c2-11e9-96d7-ce00061e1b83.png)
