### ISSUE TITLE
New icon for the `nlsy-links` GitHub organization

### ISSUE THREAD

**Issue by wibeasley** [nlsy-links/NlsyLinks#59]
@jrodgers28, for some reason the arbitrary icon GitHub generated for this organization is inspired by Finnish Calvinists?  I'm going to use a Vanderbilt logo.  Send me any other  logo you'd like.

![image](https://user-images.githubusercontent.com/1372890/59870081-6e658f00-935a-11e9-814b-576b26f2c3b5.png)

![vandy_logo](https://user-images.githubusercontent.com/1372890/59870147-8e954e00-935a-11e9-87da-63cd93186ed3.png)

**Comment by jrodgers28** [comment]
Vandy is good.  Or maybe an interlocked Vandy/OU/Ga Tech/Wake Forest?


Or Buzzy Bee (Ga Tech), A demon deacon, a Commadore, and the OU horse, all arm-in-arm, doing a line dance?


Better just go with Vandy.


Joe




Joe Rodgers

Department of Psychology and Human Development

Peabody College

Vanderbilt University

239 Appleton Place #552

Hobbs 202C

Nashville TN 37203


Department of Psychology

University of Oklahoma

Norman OK 73019

405-816-2941


________________________________
